spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common

jwt:
  secret-key: 2023-wanted-pre-onboarding-backend.secret_key
  token.expired-time-ms: 2592000000

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: mysql1234
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

