spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      prod:
        - common
      test:
        - common
---
spring:
  config:
    activate:
      on-profile: common

jwt:
  secret-key: 2023-wanted-pre-onboarding-backend.secret_key
  token.expired-time-ms: 2592000000

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE_IP}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    hikari.jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect=org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console